### ISSUE TITLE
error :  "The module to run \"python 3.8\" is not found among the available application modules."

### ISSUE THREAD

**Issue by EtiYoung** [novasush/fastapi-nginx-unit#1]
Hello i'm trying this query : curl -X PUT --data-binary @config.json --unix-socket /var/run/control.unit.sock http://localhost/config/

but i got an error :

{
	"error": "Invalid configuration.",
	"detail": "The module to run \"python 3.8\" is not found among the available application modules."
}

my config file look like this : 

{
    "listeners": {
        "*:80": {
            "pass": "applications/fastapi"
        }
    },

    "applications": {
        "fastapi": {
            "type": "python 3.8",
            "path": "/home/ubuntu/inference1",
            "home": "/home/ubuntu/anaconda3/envs/inference1/bin",
            "module": "application",
            "callable": "app"
        }
    }
}

the command line query i run to see the modules : ls /usr/lib/unit/modules 
gives me : 
java11.unit.so  perl.unit.so  python2.7.unit.so  python3.7.unit.so  ruby.unit.so
java8.unit.so   php.unit.so   python3.6.unit.so  python3.8.unit.so

**Comment by novasush** [comment]
Make sure the correct python version is being installed on your system
